try
{
    if(a===0)
      throw "user not found"  //to create exception
}
catch(err)
{
    console.log(err)
}
finally //will work anyway
{

}